In [ ]:
#NumPy Example
# This script demonstrates how to create a NumPy array and print its contents and type.
# It requires the NumPy library to be installed in your Python environment.

import numpy as np
arr = np.array([5, 8, 3, 10])
print(arr)
print(type(arr))
 

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
print(arr1 + arr2)  # Element-wise addition
print(list1 + list2)  # List concatenation
print(arr1 * arr2)  # Element-wise multiplication
print(list1 * 2)  # List repetition
print(arr1 * 2)  # Element-wise multiplication with scalar
print(arr1 + 2)  # Element-wise addition with scalar
print(arr1 - arr2)  # Element-wise subtraction
print(arr1 / arr2)  # Element-wise division
print(arr1 ** 2)  # Element-wise exponentiation
print(arr1 % 2)  # Element-wise modulus operation
print(arr1 // 2)  # Element-wise floor division
print(arr1 > 2)  # Element-wise comparison


[ 6  8 10 12]
[1, 2, 3, 4, 5, 6, 7, 8]
[ 5 12 21 32]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[3 4 5 6]
[-4 -4 -4 -4]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[1 0 1 0]
[0 1 1 2]
[False False  True  True]
[3 4]
[2 4]
[1 3]


In [8]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7])
print(arr1 + arr2)  # This will raise an error due to shape mismatch


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [10]:
# Square root of each element in arr1
print(np.sqrt(arr1))  # Element-wise square root

# Summation of all elements in arr1
print(np.sum(arr1))  # Sum of all elements

# Mean of all elements in arr1
print(np.mean(arr1))  # Mean of all elements

# Maximum value and minimum value in arr1
print(np.max(arr1))  # Maximum value
print(np.min(arr1))  # Minimum value

[1.         1.41421356 1.73205081 2.        ]
10
2.5
4
1


In [12]:
# 2D Array Example
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)  # Print the 2D array

# 3D Array Example
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)  # Print the 3D array

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Size of the array
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(arr2.size)  # Size of the  array
print(arr1.ndim)  # Number of dimensions of the array
print(arr2.shape)  # Shape of the array

4
1
(4,)


In [ ]:
arr_1 = np.array([[[8,3,1],[5,9,8]],[[20,10,11],[6,4,3]]]) # 3D array

print(arr_1.size)  # Size of the 3D array
print(arr_1.ndim)  # Number of dimensions of the 3D array
print(arr_1.shape)  # Shape of the 3D array

12
3
(2, 2, 3)


In [24]:
# Data type of the array

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8.5])
print(arr1.dtype)  # Print the data type of the array
print(arr2.dtype)  # Print the data type of the array with float

int64
float64


In [ ]:
# Numpy Indexing

arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1[2])  # Access the first element

arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2[1, 1])  # Access the element at second row, second column

arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3[0, 1, 0])  # Access the element at first layer, second row, first column

# Negative Indexing
print(arr_1[-1])  # Access the last element
print(arr_2[-1, -1])  # Access the last element of the last row
print(arr_3[-1, -1, -1])  # Access the last

3
5
3
5
6
8


In [30]:
# Boolean Indexing
arr_4 = np.array([1, 2, 3, 4, 5])
condition = arr_4 > 2
print(condition)  # Boolean array where condition is True
print(arr_4[condition])  # Access elements where condition is True

[False False  True  True  True]
[3 4 5]


In [ ]:
arr = np.array([30 , 10 ,40 , 50 ,20])
print(arr[(arr > 20) & (arr < 40)])  # Access elements greater than 20 and less than 40
print(arr[(arr < 20) | (arr > 40)])  # Access elements less than 20 or greater than 40
print(arr[(arr < 20) & ~ (arr > 40)]) # Access elements less than 20 and not greater than 40

[30]
[10 50]
[10]


In [53]:
temp = np.array([[31,30,28], [29,29,32], [26,24,27],[31,24, 35], [28,31,30]])

print(temp[temp>np.mean(temp)])

[31 30 32 31 35 31 30]


In [62]:
# Numpy.zeros and Numpy.ones np.full
arr_zeros = np.zeros((2, 3))  # Create a 2x3 array of zeros
print(arr_zeros)  # Print the array of zeros

arr_ones = np.zeros(5) # Create a 1D array of zeros with 5 elements 
print(arr_ones)  # Print the 1D array of zeros

arr_ones = np.ones((2, 3))  # Create a 2x3 array of ones
print(arr_ones)  # Print the array of ones


arr_full = np.full((2, 3), 7)  # Create a 2x3 array filled with the value 7
print(arr_full)  # Print the array filled with 7

arr = np.empty((2, 3))  # Create a 2x3 empty array
print(arr)  # Print the empty array (values are uninitialized)



[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [ ]:

print(np.full((2, 3), (1,2,3)))  # Create a 2x3 array filled with the tuple (1, 2, 3)

[[1 2 3]
 [1 2 3]]


In [ ]:
# Pandas Library
# Pandas is a powerful data manipulation and analysis library for Python.
# It provides data structures like Series and DataFrame for handling structured data.
import pandas as pd

# Create a Pandas Series
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)  # Print the DataFrame
print(type(df))  # Print the type of the DataFrame
print(df.loc[0 , 'Name'])  # Access the first row's 'Name' column value
print(df.iloc[0, 1])  # Access the first row's second column value
print(df.loc[2]) # Access the third row

print("")

print(df.iloc[1]) # Access the third row using integer location

print("")



      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
<class 'pandas.core.frame.DataFrame'>
Alice
25
Name    Charlie
Age          35
Name: 2, dtype: object

Name    Bob
Age      30
Name: 1, dtype: object



In [77]:
data = {'Name': ['Alice', 'Bob', 'Charlie' , 'David'],
        'Age': [25, 30, 35 , 40]}
df = pd.DataFrame(data, index=["student1", "student2", "student3" , "student4"])
print(df)  # Print the DataFrame with custom index

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40


In [3]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie' , 'David'],
        'Age': [25, 30, 35 , 40]}
df = pd.DataFrame(data, index=["student1", "student2", "student3" , "student4"])
print(df)  # Print the DataFrame with custom index
print("")
print(df.iloc[1]) 
print("")
print(df.loc['student3'])   
print("")
lst = ["student1", "student2"]
print(df.loc[lst])  # Access multiple rows using a list of labels
print("")
age_clomn = df['Age']  # Access the 'Age' column
print(age_clomn)  # Print the 'Age' column
print("")
print(df.columns)  # Print the column names of the DataFrame
print("")
print(list(df.columns))  # Convert column names to a list
print("")
print(df.index)  # Print the index of the DataFrame
print("")
print(list(df.index))  # Convert index to a list

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40

Name    Bob
Age      30
Name: student2, dtype: object

Name    Charlie
Age          35
Name: student3, dtype: object

           Name  Age
student1  Alice   25
student2    Bob   30

student1    25
student2    30
student3    35
student4    40
Name: Age, dtype: int64

Index(['Name', 'Age'], dtype='object')

['Name', 'Age']

Index(['student1', 'student2', 'student3', 'student4'], dtype='object')

['student1', 'student2', 'student3', 'student4']


In [4]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie' , 'David'],
        'Age': [25, 30, 35 , 40]}
df = pd.DataFrame(data, index=["student1", "student2", "student3" , "student4"])
print(df)  # Print the DataFrame with custom index
print("")
print(df.size)  # Print the size of the DataFrame
print("")
print(df.shape)  # Print the shape of the DataFrame (rows, columns)
print("")
print(len(df))  # Print the number of rows in the DataFrame

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40

8

(4, 2)

4


In [5]:
print(df.values)  # Print the values of the DataFrame
print("")
print(type(df.values))  # Print the type of the values in the DataFrame
print("")

[['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]
 ['David' 40]]

<class 'numpy.ndarray'>



In [7]:
print(df['Age'].mean())  # Print the mean of each column
print("")
print(df.sum())  # Print the sum of each column
print("")

32.5

Name    AliceBobCharlieDavid
Age                      130
dtype: object



In [ ]:
# Add new columns to the DataFrame

df ['city'] = ['Colombo', 'Kandy', 'Galle', 'Jaffna']  # Add a new column 'city'
df ['salary'] = [50000, 60000, 70000, 80000]  # Add another new column 'salary'
print(df)  # Print the DataFrame with the new column
print("")

             Name  Age     city  salary
student1    Alice   25  Colombo   50000
student2      Bob   30    Kandy   60000
student3  Charlie   35    Galle   70000
student4    David   40   Jaffna   80000



In [12]:
# Filtering rows in dataframe
filtered_df = df[df['Age'] > 30]  # Filter rows where 'Age' is greater than 30
print(filtered_df)  # Print the filtered DataFrame
print(type(filtered_df))  # Assuming temp is a function defined elsewhere

             Name  Age    city  salary
student3  Charlie   35   Galle   70000
student4    David   40  Jaffna   80000
<class 'pandas.core.frame.DataFrame'>


In [ ]:
filtered_df2 = df[(df['Age'] > 28) & (df['salary'] < 65000)]  # Filter rows where 'Age' is greater than 28 and 'salary' is less than 65000
print(filtered_df2)



         Name  Age   city  salary
student2  Bob   30  Kandy   60000


In [1]:
import pandas as pd

student_records = {
    'student_ID':[1001,1002,1003,1004,1005],
    'Name': ["Ayesha", "Nimal", "Tharindu", "Kasun", "Shashini"],
    'assignment_1': [78, 65, 88, 50, 80],
    'assignment_2': [85, 70, 90, 45, 75],
    'final_examm': [90, 72, 95, 60, 85]
}

df = pd.DataFrame(student_records)
print(df)
print("")

high_marks = df[df['final_examm'] > 80]
print(high_marks[['Name', 'final_examm']])
print("")

df['Average'] = (df['assignment_1'] + df['assignment_2'] + df['final_examm']) / 3
print(df)
print("")

average_max = df['Average'].max()
average_max_df = df[df['Average'] == average_max]
print(average_max_df[['Name', 'Average']])
print("")

assignment_1_total = df['assignment_1'].sum()
print(assignment_1_total)


   student_ID      Name  assignment_1  assignment_2  final_examm
0        1001    Ayesha            78            85           90
1        1002     Nimal            65            70           72
2        1003  Tharindu            88            90           95
3        1004     Kasun            50            45           60
4        1005  Shashini            80            75           85

       Name  final_examm
0    Ayesha           90
2  Tharindu           95
4  Shashini           85

   student_ID      Name  assignment_1  assignment_2  final_examm    Average
0        1001    Ayesha            78            85           90  84.333333
1        1002     Nimal            65            70           72  69.000000
2        1003  Tharindu            88            90           95  91.000000
3        1004     Kasun            50            45           60  51.666667
4        1005  Shashini            80            75           85  80.000000

       Name  Average
2  Tharindu     91.0

361


In [50]:
import pandas as pd

df = pd.read_csv("file_handling/test.csv")
print(df)

          Name  Age Occupation
0     John Doe   30   Engineer
1   Jane Smith   25    Teacher
2  Bob Johnson   40     Doctor
3  Alice Brown   35     Artist
